image: lorisleiva/laravel-docker:stable

stages:
  - build
  - test

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  only:
    - merge_requests

  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env

#npm:
#  stage: build
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}-npm
#    paths:
#      - node_modules/
#  script:
#    - npm install
#    - npm run production
#  artifacts:
#    expire_in: 1 month
#    paths:
#      - node_modules/
#      - public/css/
#      - public/js/

codestyle:
  stage: test
  dependencies: []
  script:
    - phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app

phpunit:
  stage: test
  only:
    - merge_requests
  dependencies:
    - composer
  services:
    - mysql:5.7
  script:
    - php artisan migrate
    - phpunit --coverage-text --colors=never
    - php artisan migrate
    - vendor/bin/phpunit --coverage-text --colors=never
